language: c
compiler: gcc

before_install:
  - sudo apt-get -y install libgsl0-dev
  - sudo apt-get -y install python3-venv

before_script:
  - git clone https://github.com/sampotter/cgreen
  - cd cgreen; make; sudo make install; cd -
  - python3 -m venv .
  - source bin/activate
  - echo XXX
  - python -c "from distutils import sysconfig; print(sysconfig.get_config_vars('CC', 'CXX', 'OPT', 'CFLAGS', 'BASECFLAGS', 'LDFLAGS', 'CCSHARED', 'LDSHARED', 'SO'))"
  - echo XXX
  - pip install cython

script:
  - ./quick_build.sh
