language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get -y install libgsl0-dev
  - sudo apt-get -y install python3-venv
before_script:
  # Set up cgreen manually
  - git clone https://github.com/sampotter/cgreen
  - cd cgreen; make; sudo make install; cd -
  - sudo ldconfig # ...
  # Set up tetgen manually
  - wget https://www.umiacs.umd.edu/~sfp/tetgen1.6.0.zip
  - unzip tetgen1.6.0.zip
  - cd tetgen1.6.0; make -j; cd -; mkdir Build; mv tetgen1.6.0 Build
  # Activate venv and install necessary Python packages
  - python3 -m venv .
  - source bin/activate
  - pip install -r requirements-py35.txt
  - pip install -r examples/requirements-py35.txt
script:
  # Build everything and run the unit tests
  - ./quick_build.sh
  - ./quick_test.sh
  # Run stress test
  - REBUILD=1 ./stress_test.sh
